[project]
name = "tqa-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lmstudio>=1.3.1",
    "simplejson>=3.20.1",
    "tabulate>=0.9.0",
    "tiktoken>=0.9.0",
]
